### ISSUE TITLE
Can i add my developed CLI package to this collection?

### ISSUE THREAD

**Issue by shan-shaji** [invertase/dart-cli-utilities#1]

**Comment by Ehesp** [comment]
Could you add some context? What sort of packages? Are they currently open source etc?

**Comment by shan-shaji** [comment]
Hey @Ehesp , yes the package is currently open source and it is a terminal spinner package.

You can access the package [here](https://github.com/shan-shaji/slug)

**Comment by shan-shaji** [comment]
Hey @Ehesp Closing this issue.
