### ISSUE TITLE
Documentation link in `README.md` is broken.

### ISSUE THREAD

**Issue by bhattabhi013** [invertase/dart-cli-utilities#7]
Documentation link in `README.md` is broken and doesn't redirect to the website
Screenshot:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/47862474/194365244-63dc2858-3f2b-438a-aa91-37530e1f91bc.png">

**Comment by bhattabhi013** [comment]
@spydon , should I redirect [here](https://dart.dev/tutorials/server/get-started) on the documentation click?

**Comment by spydon** [comment]
The link that you provided is not for this tool.
I'm not sure there ever was a doc site for `dart-cli-utilities`, so the link should most likely just be removed, but someone from invertase would have to confirm that.

**Comment by Salakar** [comment]
Removed the dead links, thanks
